# Generated by Django 4.2.1 on 2023-05-06 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="cityname",
            options={
                "ordering": ["city_name"],
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.AlterModelOptions(
            name="cityobjects",
            options={
                "ordering": ["name"],
                "verbose_name": "Городской бъект",
                "verbose_name_plural": "Городские объекты",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
        migrations.AddField(
            model_name="cityname",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="city.address",
                verbose_name="Адрес",
            ),
        ),
    ]
