# Generated by Django 4.2.1 on 2023-05-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0002_alter_address_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cityname",
            name="address",
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="city",
                to="city.cityname",
                verbose_name="Город",
            ),
        ),
    ]
