# Generated by Django 4.2.1 on 2023-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0003_remove_cityname_address_address_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cityobjects",
            name="address",
        ),
        migrations.AddField(
            model_name="cityname",
            name="address",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cityname",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
