# Generated by Django 4.2.1 on 2023-05-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0004_remove_cityobjects_address_cityname_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cityname",
            name="address",
        ),
        migrations.RemoveField(
            model_name="cityname",
            name="number",
        ),
        migrations.AddField(
            model_name="cityobjects",
            name="address",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cityobjects",
            name="address_number",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
