# Generated by Django 4.2.1 on 2023-05-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0005_remove_cityname_address_remove_cityname_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cityobjects",
            name="address",
            field=models.CharField(max_length=250, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="cityobjects",
            name="address_number",
            field=models.IntegerField(verbose_name="Номер дома"),
        ),
        migrations.AlterField(
            model_name="cityobjects",
            name="contact",
            field=models.CharField(max_length=12, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="cityobjects",
            name="description",
            field=models.TextField(verbose_name="Описание заведения"),
        ),
        migrations.AlterField(
            model_name="cityobjects",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название заведения"),
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
